### ISSUE TITLE
Docs page uses mixed content and looks bad

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/FSharp.Linq.ComposableQuery#16]
The docs page:

https://fsprojects.github.io/FSharp.Linq.ComposableQuery/

Makes requests to `http` resources that are blocked in latest FF and Chrome. They should be upgraded to https.

**Comment by jamescheney** [comment]
Thanks.  This page is (was) generated by scripts in `docs`, and I don't have a setup that runs them at the moment.  I've tried manually editing the web pages... give it a minute.
